### ISSUE TITLE
wrong spelling of NextJS 

### ISSUE THREAD

**Issue by nobleknightt** [thefstalphabet/portfolio-v4#8]
![image](https://github.com/user-attachments/assets/1a2aef6b-92d9-46e5-8e8d-ee9f255f161a)

Hi, you have wrong spelling of NextJS (or maybe a wrong logo for NestJS) in your portfolio.

**Comment by thefstalphabet** [comment]
Hi, Thanks for pointing that out.

**Comment by nobleknightt** [comment]
You're welcome!

**Comment by nobleknightt** [comment]
Nice portfolio you have. Looks similar to leerob's.

**Comment by thefstalphabet** [comment]
Thanks!
